### PR TITLE
Add linux aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel build support.
related to #34. @lmdu, could you please review this PR?

### CODE REVIEW

**Comment by odidev** [comment]
@lmdu  Could you please have a look at this PR?

**Comment by lmdu** [comment]
We almost never use linux aarch64 to perform bioinformatics analysis. Can it process very large genome Fasta files?

**Comment by odidev** [comment]
I have tested with fasta files available in readme and in tests but I need a sample for very large genome fasta file to test it in on aarch64. Could you please provide the same if you have any sample?

**Comment by lmdu** [comment]
We have added support for aarch64 in new versions.

**Pull request closed without merging**
